config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  root to: 'pages#home'
  resources :performances do
    resources :attendance, only: [:create]
    resources :comment, only: [:create]
    resources :contributions, only: :create
  end

  resources :profiles, only: [ :show, :edit, :update ]
  # For creating a new contribution
  resources :contributions, only: [ :show ] do
    resources :payments, only: [:new, :create]
  end

  resources :users, only: [:edit, :update]
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  # skip_before_action :authenticate_user!, only: [ :edit ]

  def show
    @user = User.find(params[:id])
    @performances = @user.performances
    @playing_now = playing_now?
    @social_media_links = get_social_media_array
    @contribution = Contribution.new
    @profile_banner = @user.performances.last&.photo
    if @performances.length > 0
      @performance = @performances.last
    else
      @performance = Performance.new(id: Performance.last.id)
    end
    authorize @user
  end

  def edit
    @user = User.find(params[:id])
    @social_media_links = get_social_media_array
    authorize @user
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    @user.update(user_params)
    @user.social_media_links = params_social_media_links
    if @user.save
      redirect_to profile_path(@user)
    else
      render :edit
    end
  end
  private

  def user_params
    params.require(:user).permit(:soundcloud, :youtube, :avatar, :email, :artist_name, :default_performance_photo, :artist_description, :social_media_links)
  end

  def playing_now?
    if @performances.any?
      if DateTime.now > @performances.last.start_time && DateTime.now < @performances.last.end_time
        true
      else
        false
      end
    end
  end

  def params_social_media_links
    social_media = params.require(:social_media).permit(:yt, :in, :tw, :fb)
    social_media_links = []
    social_media.each do |l|
      social_media_links << l[1]
    end
    social_media_links.join("$%$")
  end

  def get_social_media_array
    if @user.social_media_links.present?
      return @user.social_media_links.split("$%$")
    else
      return []
    end
  end

end

app/views/profiles/edit.html.erb
<div class="container" style="margin-bottom: 70px;">
    <%= simple_form_for @user, url: profile_path, method: :patch do |f| %>
        <%= f.input :avatar %>
        <h4>Social Media Links</h4>
        <% yt_link = @social_media_links[0].present? ? @social_media_links[0] : "" %>
            <div class="profile_edit_social_links">
              <%= label "social_media[yt]", "Youtube Link" %>
              <%= text_field_tag "social_media[yt]", yt_link %>
            </div>
            <% insta_link = @social_media_links[1].present? ? @social_media_links[1] : "" %>
            <div class="profile_edit_social_links">
              <%= label "social_media[in]", "Instagram Link"  %>
              <%= text_field_tag "social_media[in]", insta_link %>
            </div>
            <% twitter_link = @social_media_links[2].present? ? @social_media_links[2] : "" %>
            <div class="profile_edit_social_links">
              <%= label "social_media[tw]", "Twitter Link" %>
              <%= text_field_tag "social_media[tw]", twitter_link %>
            </div>
            <% fb_link = @social_media_links[3].present? ? @social_media_links[3] : ""%>
          <div class="profile_edit_social_links">
            <%= label "social_media[fb]", "Facebook Link" %>
            <%= text_field_tag "social_media[fb]", fb_link %>
          </div>

        <h4>Embed your videos or music</h4>
          <%= f.input :youtube, label:"Embedded Youtube Video" %>
          <%= f.input :soundcloud, label:"Embedded Your SoundCloud Video" %>
          <%= f.input :artist_name %>
          <%= f.input :artist_description%>
          <%= f.input :default_performance_photo %>
          <%= f.submit %>
    <% end %>
</div>

app/views/profiles/show.html.erb
<div class="profile-show">
  <!-- Top Section: General Infos about the artist -->
  <div class="profile-bg" style="background-image: linear-gradient(-120deg, rgba(0, 0, 0, 0.6) 0%, rgba(0, 0, 0,0.6) 50%), url(<%= @profile_banner.nil? ? image_path("4.jpg") : @profile_banner %>)">
  <div class="profile-overlay-wrapper container">
    <div class="artist-desc" style="justify-content: flex-start; align-items: flex-start;">

      <div class="artist-avatar profile-avatar" style="background-image: url('<%= cl_image_path @user.avatar, crop: :fill %>'); "></div>
      <div >
        <h2><%= @user.artist_name %></h2>
        <div class="artist-under-desc" >
          <% if @playing_now %>
          <% if @user.performances.last.genre.performance_type == "Music" %>
          <p class="green">Playing now</p>
          <% else %>
          <p class="green">Performing now</p>
          <% end %>
          <% end %>
        </div>
      </div>

    </div>


    <p><%= @user.artist_description %></p>


  </div>

  </div>

  <div class="container">

    <div class="profile-contribute">
      <% if current_user.present? %>
      <button type="button" class="socialbtns" data-toggle="modal" data-target="#contribute-modal" id="contribute-button" data-modal="<%= @contribution.errors.messages.any? %>">
        <i class=" fasc fas fa-hand-holding-usd contribute-button" aria-hidden="true"><p class="icon-text" style="font-size: 18px !important;">Contribute</p></i>
      </button>
      <% else %>
      <p class="italic">Please sign in to <strong>attend</strong> or to <strong>contribute</strong></p>
      <% end %>
    </div>

    <h4>  <%= @user.artist_name %>‘s previous performances</h4>
    <!-- Previous performances of tee artist -->
    <div class="">
      <div class="swiper-container" data-slider="artist_show">
        <!-- Additional required wrapper -->
        <div class="swiper-wrapper" style="margin-bottom: 30px;">
          <!-- Slides -->
          <% @performances.each do |performance| %>
          <div class="swiper-slide">
            <%= link_to performance_path(performance) do %>
            <div class="card">
              <div class="card-bg-img" style="background-image: url('<%= cl_image_path(performance.photo_url, crop: :fill) %>')"></div>
              <div class="card-description">

                <p><i class="fas fa-map-pin"></i> &nbsp; <i>
                
                <% if performance.location.present? %>
                  <%= performance.location.split(',').first.truncate(20) %>
                <% else %>
                  <%= "Berlin" %>
                <% end %>
                
                </i></p>
                <% start_time = performance.start_time %>
                <% end_time = performance.end_time %>
                <div class="card-time-container card-time">
                  <p class="card-time"><i class="far fa-clock"></i> <strong><%= start_time.strftime("%a %m/%d/%y")  %></strong></p>
                </div>
              </div>
            </div>
            <% end %>
          </div>
          <% end %>

        </div>

      </div>

    </div>
  </div>




  <!-- Showcase-->
  <div class="profile-showcase">
    <% if @user.youtube.present? || @user.soundcloud.present? %>
    <h4> Showcase</h4>
    <div class="media-container container">
      <% if @user.youtube.present? %>
      <p>Check me out on YouYube</p>
      <div class="aspect-ratio">
        <iframe src="<%= @user.youtube %>" frameborder="0"></iframe>
      </div>
      <% end %>

      <% if @user.soundcloud.present? %>
      <p>Check me out on Soundcloud</p>

      <div class="aspect-ratio">
        <iframe src="<%= @user.soundcloud %>" frameborder="0"></iframe>

      </div>
      <% end %>
    </div>
    <% end %>
  </div>


  <!-- SocialMedia -->
      <div class="container">
        <% if @social_media_links.present? %>
        <h4>Social Media Links</h4>
        <div class="social-media-container">

          <% if @social_media_links[0] %>
          <a href="<%= @social_media_links[0] %>">
            <div class="youtube-icon social_media_icon"></div>
          </a>
          <% end %>
          <% if @social_media_links[1] %>
          <a href="<%= @social_media_links[1] %>">
            <div class="instagram-icon social_media_icon"></div>
          </a>
          <% end %>
          <% if @social_media_links[2] %>
          <a href="<%= @social_media_links[2] %>">
            <div class="twitter-icon social_media_icon"></div>
          </a>
          <% end %>
          <% if @social_media_links[3] %>
          <a href="<%= @social_media_links[3] %>">
            <div class="facebook-icon social_media_icon"></div>
          </a>
          <% end %>
        <% end %>
      </div>

      </div>



    <br>
  <div class="container">
    <% if policy(@user).edit? %>
    <%= link_to 'Edit Profile', edit_profile_path(@user), class: 'btn btn-warning btn-home btn-height-adjust'%>
    <% end %>
  </div>


<div class="container">
  <%= link_to performances_path, class: 'back-link' do %>
  <i class="fas fa-arrow-left back-arrow profile-back-arrow"></i>
  <% end %>
</div>


  </div>





  <!-- Modal -->
  <div class="modal fade" id="contribute-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Make a Contribution</h4>
        </div>
        <%= simple_form_for([@performance, @contribution]) do |f| %>
        <div class="modal-body">
          <p>Select an amount:</p>
          <div class="contributions-flex">
            <div class="contribute-option">
              <%= f.radio_button :amount, "1€" %>
              <%= f.label :amount, :value => "true" do %>
              <p>1€</p>
              <i class="fas fa-coins"></i>
              <% end %>
            </div>
            <div class="contribute-option">
              <%= f.radio_button :amount, "2€" %>
              <%= f.label :amount, :value => "true" do %>
              <p>2€</p>
              <i class="fas fa-coins"></i>
              <% end %>
            </div>
            <div class="contribute-option">
              <%= f.radio_button :amount, "5€" %>
              <%= f.label :amount, :value => "true" do %>
              <p>5€</p>
              <i class="fas fa-money-bill"></i>
              <% end %>
            </div>
            <div class="contribute-option">
              <%= f.radio_button :amount, "10€" %>
              <%= f.label :amount, :value => "true" do %>
              <p>10€</p>
              <i class="fas fa-money-bill"></i>
              <% end %>
            </div>

          </div>

          <%= f.input :message %>

          <%= f.input :artist_id, as: :hidden, input_html: { value: @user.id } %>

        </div>
        <div class="modal-footer">
          <%= button_tag type: 'submit', class:"socialbtns button-fix" do %>
          <i class=" fasc fas fa-hand-holding-usd contribute-button" aria-hidden="true"><p class="icon-text" style="font-size: 18px !important;">Contribute</p></i>
          <% end %>
        </div>
        <% end %>
      </div>
    </div>
  </div>

</div>