config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  root to: 'pages#home'
  resources :performances do
    resources :attendance, only: [:create]
    resources :comment, only: [:create]
    resources :contributions, only: :create
  end

  resources :profiles, only: [ :show, :edit, :update ]
  # For creating a new contribution
  resources :contributions, only: [ :show ] do
    resources :payments, only: [:new, :create]
  end

  resources :users, only: [:edit, :update]
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="mobile-footer hidden-sm hidden-md hidden-lg">
  <div class="link-box">
    <!-- Explore -->
    <div class="icon-box">
      <%= link_to performances_path do %>
         <i class="fas fa-search footer-icon"></i>
          <% if user_signed_in? %>
          <% if current_user.artist %>
          <br>
          <% end %>
          <% end %>
           <%= t(".profile", default: "EXPLORE") %>
      <% end %>
    </div>

    <!-- Profile -->
    <% if user_signed_in? %>
      <% if current_user.artist %>
      <div class="icon-box">
        <%= link_to profile_path(current_user) do %>
         <i class="fa fa-user footer-icon"></i>
          <% if user_signed_in? %>
          <% if current_user.artist %>
          <br>
          <% end %>
          <% end %>
          <%= t(".profile", default: "PROFILE") %>
          <% end %>
      </div>
      <!-- New Performance -->
      <div class="icon-box">
        <%= link_to new_performance_path do %>
          <i class="fas fa-plus footer-icon"></i>
          <% if user_signed_in? %>
          <% if current_user.artist %>
          <br>
          <% end %>
          <% end %>
           <%= t(".newperformance", default: "POST") %>
        <% end %>
      </div>
        <% end %>
    <% end %>

    <!-- Setting -->
    <% if user_signed_in? %>
      <div class="icon-box footer-icon">
        <%= link_to edit_user_registration_path do %>
          <i class="fa fa-cog footer-icon"></i>
          <% if user_signed_in? %>
          <% if current_user.artist %>
          <br>
          <% end %>
          <% end %>
           <%= t(".settings", default: "SETTINGS") %>
        <% end %>
      </div>
      <% end %>

    <!-- Log out-->
    <% if user_signed_in? %>
      <div class="icon-box">
        <%= link_to destroy_user_session_path, method: :delete do %>
          <i class="fas fa-sign-out-alt footer-icon"></i>
          <% if user_signed_in? %>
          <% if current_user.artist %>
          <br>
          <% end %>
          <% end %>
           <%= t(".sign_out", default: "LOG OUT") %>
        <% end %>
      </div>
    <% end %>

    <!-- Log in / sign up -->
    <% if !user_signed_in? %>
      <div class="icon-box">
        <%= link_to t(".sign_in", default: "LOG IN"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
      </div>
      <div class="icon-box">
        <a href="#" id="signup-button" class= "navbar-wagon-item navbar-wagon-link">SIGN UP</a>
      </div>
    <% end %>

  </div>
</div>

app/views/shared/_icon.html.erb
<br/>
<div align="center" class="socialbtns">
<ul>
  <li><a href="#" class="fab fa-facebook-square"></a></li>
<li><a href="#" class="fas fa-walking"></a><p class="icon-text">I go</p></li>
<li><a href="#" class="fab fa-youtube"></a></li>
<li><a href="#" class="fab fa-instagram"></a></li>
<li><a href="#" class="fas fa-search"></a></li>

<li><a href="#" class="fas fa-plus"></a><p class="icon-text">Attend</p></li>
<li><a href="#" class="fas fa-hand-holding-usd"></a><p class="icon-text">Contribute</p></li>
</ul>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to performances_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo_busk.svg", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>
      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= cl_image_tag current_user.avatar, secure: true, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">

            <!-- Navbar items only for Artists-->
            <% if current_user.artist %>
            <li>
              <%= link_to profile_path(current_user) do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to new_performance_path do %>
                <i class="fas fa-plus"></i> <%= t(".newperformance", default: "New Performance") %>
              <% end %>
            </li>
            <% end %>

            <li>
              <%= link_to edit_user_registration_path do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <a href="#" id="signup-button" class= "navbar-wagon-item navbar-wagon-link">Sign Up</a>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
  <% if user_signed_in? %>
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" style="color: gray" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">

       <!-- Navbar items only for artists -->
        <% if current_user.artist %>

        <li>
          <%= link_to profile_path(current_user) do %>
            <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
          <% end %>
        </li>
        <li>
          <%= link_to new_performance_path do %>
            <i class="fas fa-plus"></i> <%= t(".newperformance", default: "New Performance") %>
          <% end %>
        </li>

        <% end %>

        <li>
          <%= link_to edit_user_registration_path do %>
            <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
          <% end %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
          <% end %>
        </li>
      </ul>
    </div>
  <% else %>
    <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <a href="#" id="signup-button" class= "navbar-wagon-item navbar-wagon-link">Sign Up</a>
  <% end %>
  </div>
</div>

app/views/shared/_navbar_hidden.html.erb
<div class="navbar-wagon hidden-xs">
  <!-- Logo -->
  <%= link_to performances_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo_busk.svg", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>
      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= cl_image_tag current_user.avatar, secure: true, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">

            <!-- Navbar items only for Artists-->
            <% if current_user.artist %>
            <li>
              <%= link_to profile_path(current_user) do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to new_performance_path do %>
                <i class="fas fa-plus"></i> <%= t(".newperformance", default: "New Performance") %>
              <% end %>
            </li>
            <% end %>

            <li>
              <%= link_to edit_user_registration_path do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <a href="#" id="signup-button" class= "navbar-wagon-item navbar-wagon-link">Sign Up</a>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
  <% if user_signed_in? %>
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" style="color: gray" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">

       <!-- Navbar items only for artists -->
        <% if current_user.artist %>

        <li>
          <%= link_to profile_path(current_user) do %>
            <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
          <% end %>
        </li>
        <li>
          <%= link_to new_performance_path do %>
            <i class="fas fa-plus"></i> <%= t(".newperformance", default: "New Performance") %>
          <% end %>
        </li>

        <% end %>

        <li>
          <%= link_to edit_user_registration_path do %>
            <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
          <% end %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
          <% end %>
        </li>
      </ul>
    </div>
  <% else %>
    <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <a href="#" id="signup-button" class= "navbar-wagon-item navbar-wagon-link">Sign Up</a>
  <% end %>
  </div>
</div>

app/views/shared/_searchbar.html.erb
<div class="search">

      <div class="search-bar">
        <div class="search-icon">
          <i class="fa fa-search"></i>
        </div>
        <div class="search-field">
         <%= form_tag performances_path, method: :get do %>
         <%= text_field_tag :query,
         params[:query],
         class: "form-text",
          placeholder: "Search by city..."
          %>
          <% end %>
        </div>
      </div>

  </div>

app/views/shared/_signup.html.erb
<div class="signup">
  <i class="fas fa-arrow-left signup-back"></i>
  <% user = User.new %>
  <ul id="signup-nav">
    <li data-index=0 >Email</li>
    <li data-index=1 >Password</li>
    <li data-index=2 >Avatar</li>
    <li data-index=3 >Are You An Artist?</li>
    <li data-index=4 >Artist Name</li>
    <li data-index=5 >Genre</li>
    <li data-index=6 >Done</li>
  </ul>
  <%= simple_form_for user, url: registration_path(user)   do |f| %>
  <div class="signup-view">
    <div class="signup-content">
      <%= label_tag("user[email]", "What's your email?") %>
      <%= text_field_tag("user[email]", nil, :class => 'form-control', :autocomplete => 'off') %>
      <%= submit_tag("Continue", :class => "btn btn-danger  btn-home btn-height-adjust signup-continue") %>
    </div>
  </div>
  <div class="signup-view">
    <div class="signup-content">
      <%= label_tag("user[password]", "Password") %>
      <%= password_field_tag("user[password]", nil, :class => 'form-control', :autocomplete => 'off') %>
      <%= label_tag("user[password_confirmation]", "Confirm Password") %>
      <%= password_field_tag("user[password_confirmation]", nil, :class => 'form-control', :autocomplete => 'off') %>
      <%= f.button :submit, "Continue", class: "btn-danger  btn-home btn-height-adjust signup-continue" %>
    </div>
  </div>
  <div class="signup-view">
    <div class="signup-content">
      <%= f.input :avatar, label: "Upload an avatar (optional)" %>
      <%= f.input :avatar_cache, as: :hidden %>
      <%= f.button :submit, "Continue", class: "btn-danger  btn-home btn-height-adjust signup-continue" %>
    </div>
  </div>
  <div class="signup-view">
    <div class="signup-content">
      <p>Are you an artist?</p>
      <%= hidden_field_tag "user[artist]", "", :class => 'signup-artist-hidden' %>
      <%= f.button :submit, "Yes", class: "btn-danger  btn-home btn-height-adjust signup-continue signup-split" %>
      <%= f.button :submit, "No", class: "btn-danger  btn-home btn-height-adjust signup-continue signup-split" %>
    </div>
  </div>

  <div class="signup-view">
    <div class="signup-content">
      <%= label_tag("user[artist_name]", "What's your artist alias?") %>
      <%= text_field_tag("user[artist_name]", nil, :class => 'form-control', :autocomplete => 'off') %>
      <%= f.button :submit, "Continue", class: "btn-danger  btn-home btn-height-adjust signup-continue" %>
    </div>
  </div>
  <div class="signup-view">
    <div class="signup-content">
      <%= label_tag("genre", "What's the genre?") %>
      <%= text_field_tag("genre", nil, :class => 'form-control', :autocomplete => 'off') %>
      <%= f.button :submit, "Continue", class: "btn-danger  btn-home btn-height-adjust signup-continue" %>
    </div>
  </div>
  <div class="signup-view">
    <div class="signup-content">
      <p>You're all done!</p>
      <%= f.button :submit, "Continue", class: "btn-danger btn-home btn-height-adjust " %>
    </div>
  </div>
  <% end %>

</div>