config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  root to: 'pages#home'
  resources :performances do
    resources :attendance, only: [:create]
    resources :comment, only: [:create]
    resources :contributions, only: :create
  end

  resources :profiles, only: [ :show, :edit, :update ]
  # For creating a new contribution
  resources :contributions, only: [ :show ] do
    resources :payments, only: [:new, :create]
  end

  resources :users, only: [:edit, :update]
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_contribution

  def new
    authorize @contribution
  end

  def create
    customer = Stripe::Customer.create(
    source: params[:stripeToken],
    email:  params[:stripeEmail]
  )

  charge = Stripe::Charge.create(
    customer:     customer.id,   # You should store this customer id and re-use it.
    amount:       @contribution.amount_cents,
    description:  "Payment for artist #{@contribution.artist_id} for order #{@contribution.id}",
    currency:     @contribution.amount.currency
  )
  authorize @contribution
  @contribution.update(payment: charge.to_json, state: 'paid')
  # email! 
  @recipient = @contribution.artist
  @donor = @contribution.user
  @amount = @contribution.amount_cents
  @message = @contribution.message
  ContributionMailer.contribute(@recipient, @donor, @amount, @message).deliver_now

  redirect_to contribution_path(@contribution)

rescue Stripe::CardError => e
  flash[:alert] = e.message
  redirect_to new_contribution_payment_path(@contribution)
  end

  private

  def set_contribution
    @contribution = current_user.sent_contributions.where(state: 'pending').find(params[:contribution_id])
  end

end

app/views/payments/new.html.erb
<!-- Half Banner -->
<div class="banner-half-page" style="background-image: linear-gradient(-190deg, rgba(130,130,130,0.5) 0%, rgba(0,0,10, 0.5) 100%), url('<%= image_path '7.jpg' %>');">

  <div class="banner-content">
    <div class="avatar-on-banner" style="background-image: url('<%= cl_image_path @contribution.artist.avatar, crop: :fill, secure: true %>')"></div>
    <h3 class='banner-font'><%= @contribution.artist.artist_name %></h3><br>
  </div>

</div>

<!-- Container half page -->
<div class="container container-half-page text-center">
  <h4>Review your Contribution</h4>


  <div>
    <i class="far fa-money-bill-alt icon-big-black"></i>
    <p>Amount: <%= humanized_money_with_symbol(@contribution.amount) %> </p>
  </div>
  <div>
    <i class="far fa-envelope-open icon-big-black"></i>
    <p>Message: <%= @contribution.message %> </p>
  </div>

  <!-- Stripe payment -->
  <div class="padding-top">
    <%= form_tag contribution_payments_path(@contribution) do %>
    <div>

      <i class="far fa-credit-card icon-padding icon-big-black"></i>
      <br>

      <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
      data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
      data-name="My Contribution"
      data-email="<%= current_user.email %>"
      data-description="Contribution to an artist"
      data-amount="<%= @contribution.amount_cents %>"
      data-currency="<%= @contribution.amount.currency %>">
    </script>

    <% end %>
  </div>

</div>