config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  root to: 'pages#home'
  resources :performances do
    resources :attendance, only: [:create]
    resources :comment, only: [:create]
    resources :contributions, only: :create
  end

  resources :profiles, only: [ :show, :edit, :update ]
  # For creating a new contribution
  resources :contributions, only: [ :show ] do
    resources :payments, only: [:new, :create]
  end

  resources :users, only: [:edit, :update]
end

app/models/performance.rb
class Performance < ApplicationRecord
  belongs_to :user
  belongs_to :genre
  has_many :attendances, dependent: :destroy
  has_many :comments, dependent: :destroy
  # Validations
  # validates :location, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :description, presence: true, length: { maximum: 80 }
  validates :genre, presence: true
  # Geocode
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
  # Cloudinary
  mount_uploader :photo, PhotoUploader
end

app/controllers/performances_controller.rb
class PerformancesController < ApplicationController
  before_action :authenticate_user!, except: [ :index, :show ]
  before_action :set_performance, except: [ :index, :new, :create ]

  def new
    @performance = Performance.new
    authorize @performance
  end

  def create
    @performance = Performance.new(performance_params)
    @performance.user = current_user
    if @performance.save
      redirect_to profile_path(current_user)
    else
      render :new
    end
    authorize @performance
  end

  def index
    @performances = policy_scope(Performance)

    policy_scope(Performance)
    if params[:query].present?
      sql_query = "location ILIKE :query"
      @performances = Performance.where(sql_query, query: "%#{params[:query]}%")
    else
      @performances = Performance.all.where.not('performances.location' => nil)
    end

    @markers = @performances.map.with_index do |performance, index|
      {
        lat: performance.latitude,
        lng: performance.longitude,
        performance: performance,
        index: index
      }
    end
  end

  def show
    @attendances = @performance.attendances.order(:id).limit(6);
    # @attendance_numbers = @performance.attendances.count
    @attendance = Attendance.new
    authorize @performance
    @contribution = Contribution.new
    @markers = [{
        lat: @performance.latitude,
        lng: @performance.longitude
          }]
    @duration = duration(@performance)
    @playing_now = playing_now?
    @comment = Comment.new(performance: @performance)
    @comments = @performance.comments.order(id: :desc).limit(5)
  end

  def edit
    authorize @performance
  end

  def update
    authorize @performance
  end

  def destroy
    authorize @performance
  end

  private

  def set_performance
    @performance = Performance.find(params[:id])
  end

  def performance_params
    params.require(:performance).permit(:location, :start_time, :end_time, :description, :photo, :genre_id)
  end

  def duration(performance)
    sec_in_hours = 60 * 60
    minutes = ((@performance.end_time - @performance.start_time)/60).to_i
    hours = ((@performance.end_time - @performance.start_time)/sec_in_hours).floor
    "#{hours > 0 ? "#{hours} hours" : ""}#{minutes > 0 ? " #{minutes} minutes." : ""}"
  end

  def playing_now?
    if DateTime.now > @performance.start_time && DateTime.now < @performance.end_time
      true
    else
      false
    end
  end
end

app/views/performances/index.html.erb
<!-- Navbar that is hidden on mobile -->
  <div class="main-container">
  <div
  id="map"
  data-googlemap="performances"
  style="width: 100%;
  height: 40%;
  min-height: 40vh;
  "
  data-markers="<%= @markers.to_json %>">
</div>



  <!-- Search bar -->

  <div id="cards-performances" class="cards-container">

    <div>
      <!-- <%= render "shared/searchbar" %> -->
      <div class="search-bar">
        <div class="search-bar-icon">
          <i class="fas fa-search"></i>
        </div>
        <%= form_tag performances_path, method: :get do %>
        <%= text_field_tag :query,
        params[:query],
        class: "form-search",
          placeholder: "Explore performances in your area ..."
          %>
          <% end %>
        </div>
      </div>

      <!-- Slider main container -->

      <div class="swiper-container" data-slider="performances_index">
        <div class="swiper-wrapper">
          <% index = 0 %>
          <% @performances.each do |performance| %>
          <div class="swiper-slide" data-index=<%= index %>>
            <%= link_to performance_path(performance) do %>

            <div class="card"  data-index=<%= index %>>
              <div class="card-bg-img" style="background-image: url('<%= cl_image_path(performance.photo, crop: :fill, secure: true) %>')"></div>

              <div class="card-description">
                <p><i class="fas fa-user"></i>&nbsp;<%= performance.user.artist_name %></p>
                <p><i class="fas fa-map-pin"></i> &nbsp;<%= performance.location.split(',').first.truncate(20) %></p>

                <% start_time = performance.start_time %>
                <% end_time = performance.end_time %>
                <div class="card-time-container card-time">
                  <!-- <p class="card-time"><i class="far fa-clock"></i> <strong><%= start_time.strftime("%a %m/%d/%y")  %></strong></p> -->
                  <!-- <p class="card-time-grow"></p> -->
                  <p class="card-time"><i class="far fa-clock"></i>&nbsp; Until <%= end_time.strftime("%-I %p") %></p>
                </div>
              </div>
            </div>
            <% end %>
          </div>
          <% index += 1 %>
          <% end %>

        </div>
      </div>

    </div>

</div>
<!-- Footer for mobile device -->
<%= render 'shared/footer' %>

app/views/performances/new.html.erb
<div class="container">
  <h2>Create a performance</h2>
  <%= simple_form_for @performance do |f| %>
    <%= f.input :location %>

    <%= f.input :start_time, as: :string, required: false, input_html: {class: "datepicker"} %>
    <%= f.input :end_time, as: :string, required: false, input_html: {class: "datepicker"} %>

    <%#= f.input :start_time %>
    <%#= f.input :end_time %>
    <%= f.input :description %>
    <%= f.input :genre_id, collection: Genre.all %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
    <%= f.button :submit, "Create", class: "btn btn-warning btn-home" %>
  <% end %>
</div>

app/views/performances/show.html.erb
<!-- Navbar that is hidden on mobile -->
<div class="performance-show">

  <!-- TOP HALF (artist card)-->
  <div class="performance-photo-bg" style="background-image: linear-gradient(-120deg, rgba(0, 0, 0, 0.6) 0%, rgba(0, 0, 0,0.6) 50%), url('<%= cl_image_path @performance.photo, crop: :fill, secure: true; %>')">
    <div class="artist-overlay-card">

      <div class="artist-desc" style="justify-content: flex-start;">
        <div class="artist-avatar" style="background-image: url('<%= cl_image_path @performance.user.avatar, crop: :fill, secure: true; %>')"></div>
          <h2><%= link_to @performance.user.artist_name, profile_path(@performance.user) %></h2>
      </div>
        <!-- TO DO validate input for description to be less than 80 chars -->
        <p class="italic"><%= @performance.description.truncate(80) %></p>
      <ul class="performance-description">
        <li><i style="vertical-align: top;" class="fas fa-map-pin"></i> <div style="display:inline-block;"> <%= @performance.location.split(',').first.truncate(20) %></div></li>
        <li><i class="fas fa-music"></i><%= @performance.genre.name %></li>
        <li><i class="far fa-clock"></i><span class="playing_now">
          Until <%= @performance.end_time.strftime("%-I %p") %>
        </li>
      </ul>
    </div>

    <!-- BACK ARROW -->
    <%= link_to performances_path, class:"back-link" do %>
    <div class="flex-start">
      <i class="fas fa-arrow-left back-arrow performance-back"></i>
      <!-- <p class="italic"> View all performances near you</p> -->
    </div>
    <% end %>

   <!-- ATTENDING -->
    <div class="attending-error-container">
    </div>
    <ul class="attendance">
      <% if @attendances.length > 0 %>
        <% @attendances.each do |a| %>
        <%= render "attendance/attend", user: a.user %>
        <% end %>
      <% else %>
        <li class="italic no-attend attend-item">Be the first to attend!</li>
      <% if !current_user.present? %>  <%= link_to "Log in", new_user_session_path, class: "navbar-wagon-item italic" %><% end %>
      <% end %>
      <li class="attend-item">
        <%= simple_form_for [ @performance, @attendance ], url: performance_attendance_index_path(@performance.id), remote: true do |form| %>
          <%= form.hidden_field :performance_id, :value => @performance.id %>
          <%= button_tag type: 'submit', class:"socialbtns" do %>
            <i class="attend-button fasa fas fa-plus" aria-hidden="true"></i>
          <% end %>
        <% end %>
      </li>
    </ul>


  </div>

  <div
  id="map"
  style="width: 100%;
  height: calc(45vh - 30px);"
  data-markers="<%= @markers.to_json %>">
</div>


    <!-- PERFORMANCE INFO -->
    <div class="container">

      <div class="flex-between">
        <div class="inline">
          <div>

          </div>
          <% if current_user.present? %>
            <%= simple_form_for [ @performance, @attendance ], url: performance_attendance_index_path(@performance.id), remote: true, html: {id: :new_contribution_form} do |form| %>
              <%= form.hidden_field :performance_id, :value => @performance.id, html: {id: :hidden_attendance_input}%>

              <!-- Button trigger modal -->
              <button type="button" class="socialbtns" data-toggle="modal" data-target="#contribute-modal" id="contribute-button" data-modal="<%= @contribution.errors.messages.any? %>">
                <i class=" fasc fas fa-hand-holding-usd contribute-button" aria-hidden="true"><p class="icon-text">Contribute</p></i>

              </button>
            <% end %>
          <% else %>
            <p class="italic">Please sign in to <strong>attend</strong> or to <strong>contribute</strong></p>
          <% end %>
        </div>
      </div>


    <div class="comments">
      <h3>Comments:</h3>
      <ul>
        <% if @comments.length > 0 %>
          <% @comments.each do |comment| %>
            <%= render "comment/comment", comment: comment %>
          <% end %>
        <% else %>
          <p class="italic no-attend">No comments yet. Be the first to comment!</p>
          <% if !current_user.present? %>  <%= link_to "Log in", new_user_session_path, class: "navbar-wagon-item italic" %><% end %>
        <% end %>
      </ul>

      <% if current_user.present? %>
        <%= simple_form_for [ @performance, @comment ], url: performance_comment_index_path(@performance.id), remote: true do |form| %>
          <%= form.hidden_field :performance_id, :value => @performance.id, html: { id: "performance_"} %>

          <%= form.input :comment_text, as: :text, label: false %>
           <%#= button_tag type: 'submit', class:"socialbtns " do %>
           <%= form.button :submit, 'Post', class: 'comment-button' %>
            <!-- <i class="comment-button fasc fas fa-comment-dots" aria-hidden="true"><p class="icon-text">Comment</p></i> -->
          <%# end %>

        <% end %>
      <% else %>
      <p class="italic">Please sign in to comment</strong></p>
      <% end %>
    </div>

      </div>


    </div>
</div>


<!-- Modal -->
<div class="modal fade" id="contribute-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Make a Contribution</h4>
      </div>
      <%= simple_form_for([@performance, @contribution]) do |f| %>
      <div class="modal-body">
        <p>Select an amount:</p>
        <div class="contributions-flex">
          <div class="contribute-option">
            <%= f.radio_button :amount, "1€" %>
            <%= f.label :amount, :value => "true" do %>
            <p>1€</p>
            <i class="fas fa-coins"></i>
            <% end %>
          </div>
          <div class="contribute-option">
            <%= f.radio_button :amount, "2€" %>
            <%= f.label :amount, :value => "true" do %>
            <p>2€</p>
            <i class="fas fa-coins"></i>
            <% end %>
          </div>
          <div class="contribute-option">
            <%= f.radio_button :amount, "5€" %>
            <%= f.label :amount, :value => "true" do %>
            5€
            <i class="fas fa-money-bill"></i>
            <% end %>
          </div>
          <div class="contribute-option">
            <%= f.radio_button :amount, "10€" %>
            <%= f.label :amount, :value => "true" do %>
            10€
            <i class="fas fa-money-bill"></i>
            <% end %>
          </div>

        </div>

        <%= f.input :message %>
        <%= f.input :artist_id, as: :hidden, input_html: { value: @performance.user.id } %>

      </div>
      <div class="modal-footer">
        <%= button_tag type: 'submit', class:"socialbtns button-fix" do %>
        <i class=" fasc fas fa-hand-holding-usd contribute-button" aria-hidden="true"><p class="icon-text" style="font-size: 18px !important;">Contribute</p></i>
        <% end %>
      </div>
      <% end %>
    </div>
  </div>
</div>